export const DELETE_ORDER_ITEM = 'DELETE_ORDER_ITEM';
export const ADD_TO_ORDERLIST = 'ADD_TO_ORDERLIST';
export const ADD_QUANTITY = 'ADD_QUANTITY';
export const SUBTRACT_QUANTITY = 'SUBTRACT_QUANTITY';
export const RESET_ORDERLIST = 'RESET_ORDERLIST';
